<!-- country selection - you need to surround this with select tags -->
    <option value="">Country</option>
    <option value="US">United States</option>
    <option value="CA">Canada</option>
    <option value="AL">Albania</option>
    <option value="DZ">Algeria</option>
    <option value="AI">Anguilla</option>
    <option value="AR">Argentina</option>
    <option value="AU">Australia</option>
    <option value="AT">Austria</option>
    <option value="BS">Bahamas</option>
    <option value="BH">Bahrain</option>
    <option value="BD">Bangladesh</option>
    <option value="BE">Belgium</option>
    <option value="BM">Bermuda</option>
    <option value="BR">Brazil</option>
    <option value="BN">Brunei</option>
    <option value="BG">Bulgaria</option>
    <option value="KY">Cayman Islands</option>
    <option value="CL">Chile</option>
    <option value="CN">China</option>
    <option value="CO">Colombia</option>
    <option value="CR">Costa Rica</option>
    <option value="HR">Croatia</option>
    <option value="DK">Denmark</option>
    <option value="DJ">Djibouti</option>
    <option value="EC">Ecuador</option>
    <option value="EG">Egypt</option>
    <option value="ET">Ethiopia</option>
    <option value="FL">Falkland Islands (Malvinas)</option>
    <option value="FJ">Fiji</option>
    <option value="FI">Finland</option>
    <option value="FR">France</option>
    <option value="PF">French Polynesia</option>
    <option value="DE">Germany</option>
    <option value="GE">Georgia</option>
    <option value="GR">Greece</option>
    <option value="GU">Guam</option>
    <option value="GT">Guatemala</option>
    <option value="HK">Hong Kong</option>
    <option value="HU">Hungary</option>
    <option value="IN">India</option>
    <option value="ID">Indonesia</option>
    <option value="IE">Ireland</option>
    <option value="IL">Israel</option>
    <option value="IT">Italy</option>
    <option value="JP">Japan</option>
    <option value="JO">Jordan</option>
    <option value="KR">Korea</option>
    <option value="KW">Kuwait</option>
    <option value="LV">Latvia</option>
    <option value="LB">Lebanon</option>
    <option value="LU">Luxembourg</option>
    <option value="MO">Macau</option>
    <option value="MY">Malaysia</option>
    <option value="MT">Malta</option>
    <option value="MX">Mexico</option>
    <option value="MA">Morocco</option>
    <option value="NL">Netherlands</option>
    <option value="AN">Netherlands Antilles</option>
    <option value="NZ">New Zealand</option>
    <option value="NI">Nicaragua</option>
    <option value="NG">Nigeria</option>
    <option value="NF">Norfolk Island</option>
    <option value="NO">Norway</option>
    <option value="OM">Oman</option>
    <option value="PK">Pakistan</option>
    <option value="PA">Panama</option>
    <option value="PN">Papua New Guinea</option>
    <option value="PY">Paraguay</option>
    <option value="PE">Peru</option>
    <option value="PH">Philippines</option>
    <option value="PL">Poland</option>
    <option value="PT">Portugal</option>
    <option value="QA">Qatar</option>
    <option value="PA">Republic of Panama</option>
    <option value="RO">Romania</option>
    <option value="RU">Russia</option>
    <option value="SC">Seychelles</option>
    <option value="SA">Saudi Arabia</option>
    <option value="SG">Singapore</option>
    <option value="ZA">South Africa</option>
    <option value="ES">Spain</option>
    <option value="SE">Sweden</option>
    <option value="CH">Switzerland</option>
    <option value="SY">Syria</option>
    <option value="TW">Taiwan</option>
    <option value="TZ">Tanzania</option>
    <option value="TH">Thailand</option>
    <option value="TN">Tunisia</option>
    <option value="TR">Turkey</option>
    <option value="TC">Turks and Caicos Islands</option>
    <option value="TM">Turkmenistan</option>
    <option value="UG">Uganda</option>
    <option value="GB">United Kingdom</option>
    <option value="AE">United Arab Emirates</option>
    <option value="US">United States</option>
    <option value="UY">Uruguay</option>
    <option value="UZ">Uzbekistan</option>
    <option value="VE">Venezuela</option>
    <option value="VN">Vietnam</option>
    <option value="YE">Yemen</option>
    <option value="ZW">Zimbabwe</option>
