<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Sakai Elections</title>
<meta name="description" content="Sakai - www.sakaiproject.org, Community Source Software for Education." />
<meta name="keywords" content="sakai, sakaiproject.org, sakaiproject, Sakai, Community Source, Open Source, open-open, educational software, collaborative" />
<meta name="Generator" content="Mambo - Copyright 2000 - 2005 Miro International Pty Ltd.  All rights reserved." />
<meta name="robots" content="index, follow" />
<meta http-equiv="Content-Type" content="text/html;>charset=iso-8859-1" />
<link rel="stylesheet" href="http://www.sakaiproject.org/facebook/template_css.css" type="text/css"/><link rel="alternate" title="sakaiproject.org" href="http://www.sakaiproject.org/index2.php?option=com_rss&no_html=1" type="application/rss+xml" />
<link rel="stylesheet" href="http://www.sakaiproject.org/facebook/facebook2.css" type="text/css"/>
<script language="JavaScript" type="text/javascript">
<!--
function popup(url,name,w,h){
settings="width=" + w + ",height=" + h + ",scrollbars=yes,location=no,directories=no,status=no,menubar=no,toolbar=no,resizable=yes";
win=window.open(url,name,settings);
}
//-->
</script>

<style type="text/css">
 input {
font-size: 12px;
padding-left: 3px;
}
#searchBar1{
border-top: 1px solid #eee;
border-bottom:1px solid #ccc;

padding: 0px spx;
margin: 0;
}

.searchBar, .searchBar form, .searchBar input{
padding: 0px 0px 0px 0px;
margin: 0px;


}
.searchBar form{
color: #660000;
}

#photos {
width: 100%;
padding:0px;
margin-top: 0px;
margin-left: 0px;

}

#photos a, #photos a:link, #photos a:visited{
font-weight: normal;
color: #4E6483;
color: #660000;


}
#photos a:hover{
font-weight: normal;
color: #ffcc33;

}

#help p, #help2 p{
width: 140px; 
border: 1px solid #eee;
font-size: 11px;
padding: 3px 3px 3px 10px;
text-align: left;


}
.goback a{ color: #660000;


}



#menu {width:100%;
padding: 0px 0px 0px 0px;
margin:0px;}


#menu td {
border-bottom: 1px solid #eee;
}


#menu ul{
display: block;
text-align: left;
}

#menu li {display: block;
padding: 2px 0px 0px 0px;
text-align: left;


}

.viewmenu {width:500px;
padding: 4px 0px 4px 40px;


}
.editmenu {
padding: 4px 0px;

}

img { border:none;

padding-right: 40px;
}

#frame{
width:90%;
text-align:left;


}
#active_menu{
padding-left: 15px;
background:  url(http://www.sakaiproject.org//conferenceJune_05/regindex_files/arrow.png) no-repeat;

}



#frame img {
align: left;
padding: 0px;
border: 0px solid #eee;

}

#about, .name, .institute, .interests{
padding: 0px;

margin:0px;
}
.name {
font-size: 14px;

font-weight: bold;
padding: 10px 5px;


}

.pathway img {
padding:0px 0px 0px 10px;
}
.institute{ font-size: 12px;
padding: 10px 30px;

}
.interests {font-size: 12px;
padding: 10px  30px 10px 30px;
text-align:left;



}

div span.label{
font-weight: bold;
float: left;
width: 140px;
text-align: right;
}

div span.data{ 
text-align: left;
padding-left: 10px;

}

#info {padding: 0px 20px;

}


.centerContent{
border-left:1px solid #ccc;
padding: 10px 5px 10px 25px;
}
 
form div{ padding: 3px 0px;

}
form textarea { font-family: arial; font-size: 11px;

}
</style>
</head>

<body>
<div>
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr>  <!-- Header row begins -->
    <td class="mainHeader" width="100%">
     
     	<table width="100%" border="0" cellpadding="0" cellspacing="0">
          <tbody>
            <tr>

              <td width=180px><a href="../index.php"><img src="http://www.sakaiproject.org/conferenceJune_05/regindex_files/logoslate160x89.jfif" alt="Sakai Logo" border="0"></a> </td>

              <td><div id=header>
                  <h1>Sakai Board Elections</h1>
                  <p class=banner></p>
                </div>
              </td>
            </tr>
          </tbody>

        </table>

   </td>
   </tr> <!-- Header row ends-->
   
   <!-- Search and Navigation Bar -->

   <tr>
   <td>
      <table id="searchBar1" bgcolor="#f3f3f3" border="0" width="100%">
         <tbody>

            <tr>
              <td class="searchBar"><span class="pathway"> <img src="http://www.sakaiproject.org//conferenceJune_05/regindex_files/arrow.png" height="9" width="9"> Sakai Elections<img src="http://www.sakaiproject.org/conferenceJune_05/regindex_files/arrow.png" alt="arrow"> Nominees </span></td>
           	 <td class="searchBar" valign=top align="right">
             <!--     <form method="post" action="search.php">
                    <label> Search Nominees</label>

                    <input type="text" name="searchword" size="15" maxlength="40" value="" />
                    <input type="submit" value="go" />
                  </form>
                  -->
              </td>
            </tr>
          </tbody>
        </table>
    </td>

    </tr>  <!-- Search and Navigation Bar ends -->




<!-- Menus and Main Content - Row begins-->
   
     	<tr width=100%>
		<td>
		<table class="mainPageContent" width=100%>
		<tr>
		 <td width=160px valign=top height=400px><!-- right column starts -->
			<!-- <table width=100% class="moduletable">

     	     <tr>

             <th valign="top">Display photos</th></tr>
             
			 <tr align="left"> <td class="mainlevel"><a href=view_lastname.php>by Last Name</a></td></tr>
             <tr align="left"> <td class="mainlevel"><a href=view_recent.php>by Recent Entry</a></td></tr>
             <tr align="left"> <td class="mainlevel"><a href="view_institution.php">by Institution</a></td></tr>

       	     </table>
-->
			 
			 <table width=100% class="moduletable">
             <th  valign=top>Add or Edit Entries</th>
             <tr><td>
				<p><strong>Need help?</strong><br />If you have problems submitting your information, 
				or if you need to make changes after your information is published, please email 
				<a href="mailto:shardin@umich.edu">shardin@umich.edu</a></p>
		   		
<div height=500px>&nbsp</div>
		  	</td>

		  </tr>
		  </table>
		  
		  
	   </td>  <!-- right column ends -->