<?php

// all pages footer.inc

?>
<?php

// all pages footer.inc

?>


            <td valign="top" style="background-repeat: repeat-y; "background="../templates/austin05/images/rb.gif"></td>

            <td valign="top" style="padding-right: 8px; background-repeat: repeat-y;" background="../templates/austin05/images/shadowr.jpg">&nbsp;</td>
          </tr>
        </table>
        
        
        
        <table width="100%"  border="0" cellpadding="0" cellspacing="0" background="../templates/austin05/images/center2.jpg">
          <tr>
            <td width="26"><img src="../templates/austin05/images/left2.jpg" /></td>
            <td>
           
           
           <table width="100%"  border="0" cellspacing="0" cellpadding="0">
                <tr>

                  <td width="30" align="left"><img src="../templates/austin05/images/ltop.jpg"  border="0" /> </td>
                  <td align="center"><div class="footer"><div align="center">Copyright 2005, Sakai Project</div>
<div align="center">contact <a href="mailto:sakaiproject_webmaster@umich.edu">webmaster@sakaiproject.org</a></div>
                   </div>
                    </td>
                  <td width="30" align="right"><img src="../templates/austin05/images/rtop.jpg" border="0" /></td>
                </tr>

            </table>
            
            </td>
            <td width="26"><img src="../templates/austin05/images/right2.jpg" /></td>
          </tr>
        
  </table>
</div>
</body>
</html>