<?php

// all pages footer.inc

?>

</div></td>
                </tr>
                <tr bgcolor="#F1F1F1">
                  <td colspan="3" valign="top" style="border-top: 3px solid #FFFFFF;"></td>
                  </tr>
              </table>
             </td>
            <td valign="top" style="background-repeat: repeat-y; "background="http://www.sakaiproject.org/templates/247portal-b-brown2/images/rb.gif"></td>

            <td valign="top" style="padding-right: 8px; background-repeat: repeat-y;" background="http://www.sakaiproject.org/templates/247portal-b-brown2/images/shadowr.jpg">&nbsp;</td>
          </tr>
        </table>
        <table width="100%"  border="0" cellpadding="0" cellspacing="0" background="http://www.sakaiproject.org/templates/247portal-b-brown2/images/center2.jpg">
          <tr>
            <td width="26"><img src="http://www.sakaiproject.org/templates/247portal-b-brown2/images/left2.jpg" /></td>
            <td>
              <table width="100%"  border="0" cellspacing="0" cellpadding="0">
                <tr>

                  <td width="30" align="left"><img src="http://www.sakaiproject.org/templates/247portal-b-brown2/images/ltop.jpg"  border="0" /> </td>
                  <td align="center"><div class="footer"><div align="center">Copyright 2005, Sakai Project</div>
<div align="center">contact <a href="mailto:sakaiproject_webmaster@umich.edu">webmaster@sakaiproject.org</a></div>
                   </div>
                    </td>
                  <td width="30" align="right"><img src="http://www.sakaiproject.org/templates/247portal-b-brown2/images/rtop.jpg" border="0" /></td>
                </tr>

            </table></td>
            <td width="26"><img src="http://www.sakaiproject.org/templates/247portal-b-brown2/images/right2.jpg" /></td>
          </tr>
        </table>
      </div></td>
    </tr>
  </table>
</div>
</body>
</html>