<?php

//header information for registration page
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Sakai SEPP - Austin Conference Registration </title>
<meta name="description" content="Sakai - www.sakaiproject.org, Community Source Software for Education." />
<meta name="keywords" content="sakai, sakaiproject.org, sakaiproject, Sakai, Community Source, Open Source, open-open, educational software, collaborative" />
<meta name="Generator" content="Mambo - Copyright 2000 - 2005 Miro International Pty Ltd.  All rights reserved." />
<meta name="robots" content="index, follow" />
<meta http-equiv="Content-Type" content="text/html;>charset=iso-8859-1" />
<link rel="stylesheet" href="../../templates/austin05/css/template_css.css" type="text/css"/><link rel="alternate" title="sakaiproject.org" href="http://www.sakaiproject.org/index2.php?option=com_rss&no_html=1" type="application/rss+xml" />
<script language="JavaScript" type="text/javascript">
    <!--
    function MM_reloadPage(init) {  //reloads the window if Nav4 resized
      if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
        document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
      else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
    }
    MM_reloadPage(true);
    //-->
  </script>
<style type="text/css">
form, input {
font-size: 12px;
padding-left: 3px;
}

 form td {
padding: 5px;
}

.formlabel{ padding-right: 5px;

}

#help p, #help2 p{
width: 140px; 
border: 1px solid #eee;
font-size: 11px;
padding: 3px 3px 3px 10px;
text-align: left;


}
<!--
.Stil1 {font-size: xx-small;
	color: #FFFFFF;
}
-->
</style>
</head>

<body>
<div>
  <a name="up" id="up"></a>
  
<table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
    <td><img src="../../templates/247portal-b-brown2/images/space.gif" width="100%" height="1" /></td>
  </tr>
	<tr>
      <td><div class="background">
       
       
		 <table  width="100%" height="120" border="0" cellpadding="0" cellspacing="0" style="margin:0; padding:0;">
	<tr>
		<td>
			<img src="../../templates/austin05/images/header700x120_01.jpg" width="128" height="120" alt=""></td>
		<td>
			<img src="../../templates/austin05/images/header700x120_02.jpg" width="289" height="120" alt=""></td>
		<td>
			<img src="../../templates/austin05/images/header700x120_03.jpg" width="247" height="120" alt=""></td>
			
		<td style="background: url(../../templates/austin05/images/header700x120_04.jpg) repeat-x;" width="100%">
			</td>
		<td valign=top width="26px"  style="background: url(../../templates/austin05/images/header700x120_05.jpg) repeat-x;" >
			<img src="../../templates/austin05/images/header700x120_05.jpg"></td>
	</tr>
</table> 
<!-- end of new header -->


<!-- start of pathway -->

   <table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0" style="margin-top:-5px;">
          <tr>
            <td width="11" height="25" background="../../templates/austin05/images/shadowl.jpg"><div>
            </div></td>
            <td height="25" bgcolor="#F1F1F1" style="border-bottom: 1px solid #999999; border-top: 5px solid #FFFFFF;"><span class="pathway"><a href="../../index.php" class="pathway">Home</a> <img src="http://www.sakaiproject.org/images/M_images/arrow.png" alt="arrow" />  Registration<img src="http://www.sakaiproject.org/images/M_images/arrow.png" alt="arrow" />  SEPP Registration </span>

           </td>
            <td width="11" height="25" align="right" background="../../templates/austin05/images/shadowr.jpg">&nbsp;</td>
          </tr>
        </table>
        
        <!--end of pathway  -->


        
        <table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>          <!-- start of main content -->


          <td valign="top" style="padding-left:8px; background-repeat: repeat-y;" background="../../templates/austin05/images/shadowl.jpg">&nbsp;</td>
          <td valign="top" style="background-repeat: repeat-y;"background="../../templates/austin05/images/lb.gif">    
         
         
         <div class="leftrow">  <!-- start left row -->

           <table cellpadding="0" cellspacing="0" class="moduletable">
			<tr>
			 <th valign="top">Austin Conference</th></tr>
				

		    <tr align="left"><td><a href="http://www.sakaiproject.org/index.php?option=com_content&task=blogcategory&id=158&Itemid=495" class="mainlevel" >Conference Home</a></td></tr>
		    <tr align="left"><td><a href="http://www.sakaiproject.org/index.php?option=com_content&task=blogcategory&id=160&Itemid=496" class="mainlevel" class="mainlevel" >Registration</a></td></tr>
			<tr align="left"><td><a href="sepp.php" class="mainlevel" id="active_menu">&nbsp;&nbsp;&nbsp;&nbsp;SEPP Registration</a></td></tr>
			<tr align="left"><td><a href="https://sakaiproject.org/austin/registration/public.php" class="mainlevel">&nbsp;&nbsp;&nbsp;&nbsp;Non-Member <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Registration</a></td></tr>

			<tr align="left"><td></td></tr>
			</table>  <!-- end module table -->
			  
			  
				<table cellpadding="0" cellspacing="0" class="moduletable">
				  <tr>

					<td><p>&nbsp;</p>
					<div id=help>
	
	
					<p><strong>Need help?</strong><br />If you experience problems with this form please contact 
					<a href="mailto:shardin@umich.edu">shardin@umich.edu</a></p>
				   </div>					
				   
				   </td>
				</tr>
			 </table>  <!-- end module table -->
			 

		 </div>  <!-- end left row -->
	    </td>   <!-- end left column of main section -->

						