<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Sakai SEPP - Austin Conference Facebook </title>
<meta name="description" content="Sakai - www.sakaiproject.org, Community Source Software for Education." />
<meta name="keywords" content="sakai, sakaiproject.org, sakaiproject, Sakai, Community Source, Open Source, open-open, educational software, collaborative" />
<meta name="robots" content="index, follow" />
<meta http-equiv="Content-Type" content="text/html;>charset=iso-8859-1" />
<link rel="stylesheet" href="../../templates/austin05/css/template_css.css" type="text/css"/>
<script language="JavaScript" type="text/javascript">
    <!--
    function MM_reloadPage(init) {  //reloads the window if Nav4 resized
      if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
        document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
      else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
    }
    MM_reloadPage(true);
    //-->
  </script>
  <script language="JavaScript" type="text/javascript">
<!--
function popup(url,name,w,h){
settings="width=" + w + ",height=" + h + ",scrollbars=yes,location=no,directories=no,status=no,menubar=no,toolbar=no,resizable=yes";
win=window.open(url,name,settings);
}
//-->
</script>
<style type="text/css">
 input {
font-size: 12px;
padding-left: 3px;
}
#searchBar1{
border-top: 1px solid #eee;
border-bottom:1px solid #ccc;

padding: 0px spx;
margin: 0;
}

.searchBar, .searchBar form, .searchBar input{
padding: 0px 0px 0px 0px;
margin: 0px;


}
.searchBar form{
color: #660000;
}

#photos {
width: 100%;
padding:0px;
margin-top: 0px;
margin-left: 0px;

}

#photos a, #photos a:link, #photos a:visited{
font-weight: normal;
color: #4E6483;
color: #660000;


}
#photos a:hover{
font-weight: normal;
color: #ffcc33;

}

#help p, #help2 p{
width: 140px; 
border: 1px solid #eee;
font-size: 10px;
padding: 3px 3px 3px 10px;
text-align: left;


}
.goback a{ color: #660000;


}



#menu {width:100%;
padding: 0px 0px 0px 0px;
margin:0px;}


#menu td {
border-bottom: 1px solid #eee;
}


#menu ul{
display: block;
text-align: left;
}

#menu li {display: block;
padding: 2px 0px 0px 0px;
text-align: left;


}

.viewmenu {width:500px;
padding: 4px 0px 4px 40px;


}
.editmenu {
padding: 4px 0px;

}


#frame{
float: left;
text-align: left;
width: 130px;
height: 230px;
padding: 10px;
margin: 0px;
font-size: 10px;
}



#frame img {
padding: 0px;
border: 2px solid #eee;

}

#about, .name, .institute, .interests{
padding: 0px;

margin:0px;
}
.name {
  font-family      : Arial, Helvetica, sans-serif;
font-size: 11px;

font-weight: bold;
padding: 2px 0px 0px 0px;


}
.institute{ font-size: 11px;
font-weight: bold;
color:#666;
padding: 0px 0px;

}
.interests {
font-size: 10px;
padding: 5px  0px 0px 0px;
text-align:left;
  font-family      : Arial, Helvetica, sans-serif;

}

div span.label{
font-weight: bold;
float: left;
width: 140px;
text-align: right;
}

div span.data{ 
text-align: left;
padding-left: 10px;

}

#info {padding: 0px 20px;

}
.searchform {width:300px; 
text-align: left;
padding:0px;
margin:0px;
font-size: 10px;
color: #fff;
font-weight:bold;
text-transform: uppercase;

}

 .searchform input, .searchform submit {
padding:0px;
margin:0px;
font-size: 10px;

}

<!--
.Stil1 {font-size: xx-small;
	color: #FFFFFF;
}


-->
</style>
</head>

<body>
<div>
  <a name="up" id="up"></a>
  
<table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
    <td><img src="../../templates/austin05/images/space.gif" width="100%" height="1" /></td>
  </tr>
	<tr>
      <td><div class="background">
       
       
		 <table  width="100%" height="120" border="0" cellpadding="0" cellspacing="0" style="margin:0;  padding:0;">
	<tr>
		<td>
			<img src="../../templates/austin05/images/header700x120_01.jpg" width="128" height="120" alt=""></td>
		<td>
			<img src="../../templates/austin05/images/header700x120_02.jpg" width="289" height="120" alt=""></td>
		<td>
			<img src="../../templates/austin05/images/header700x120_03.jpg" width="247" height="120" alt=""></td>
			
		<td style="background: url(../../templates/austin05/images/header700x120_04.jpg) repeat-x;" width="100%"> <form class=searchform method="post" action="search.php">
                    <label> Search Facebook</label><br />
                    <input type="text" name="searchword" size="20" maxlength="40" value="<?php echo $_POST['searchword']?>" />
                    <input type="submit" value="go" />
                  </form>
			</td>
		<td valign=top width="26px"  style="background: url(../../templates/austin05/images/header700x120_05.jpg) repeat-x;" >
			<img src="../../templates/austin05/images/header700x120_05.jpg"></td>
	</tr>
</table> 
<!-- end of new header -->


<!-- start of pathway -->

   <table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0" style="margin-top:-5px;">
          <tr>
            <td width="11" height="25" background="../../templates/austin05/images/shadowl.jpg"><div>
            </div></td>
         <td height="25" bgcolor="#F1F1F1" style="border-bottom: 1px solid #999999; border-top: 5px solid #FFFFFF;"><span class="pathway">
         <a href="http://sakaiproject.org/index.php" class="pathway">Home</a> <img src="http://www.sakaiproject.org/images/M_images/arrow.png" alt="arrow" />
        <a href="http://www.sakaiproject.org/index.php?option=com_content&task=blogcategory&id=158&Itemid=495" class="pathway"> Austin Conference </a><img src="http://www.sakaiproject.org/images/M_images/arrow.png" alt="arrow" />
         Facebook </span>

</td>
       
            <td width="11" height="25" align="right" background="../../templates/austin05/images/shadowr.jpg">&nbsp;</td>
          </tr>
        </table>
        
        <!--end of pathway  -->


        
        <table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>          <!-- start of main content -->


          <td valign="top" style="padding-left:8px; background-repeat: repeat-y;" background="../../templates/austin05/images/shadowl.jpg">&nbsp;</td>
          <td valign="top" style="background-repeat: repeat-y;"background="../../templates/austin05/images/lb.gif">    
         
         
         <div class="leftrow">  <!-- start left row -->

                			<table cellpadding="0" cellspacing="0" class="moduletable">
							<tr>
					<th valign="top">
										Austin Conference					</th>
				</tr>
						

<tr align="left"><td><a href="http://www.sakaiproject.org/index.php?option=com_content&amp;task=blogcategory&amp;id=158&amp;Itemid=495" class="mainlevel" >Conference Home</a></td></tr>
<tr align="left"><td><a href="https://sakaiproject.org/secure/austin/facebook/index.php" class="mainlevel" id="active_menu">Austin Facebook</a></td></tr>
<tr align="left"><td>&nbsp;<br /></td></tr>
<tr align="left"><td></td></tr>
<tr align="left"><td></td></tr>
			</table>  <!-- end module table -->
			  
			  
				<table cellpadding="0" cellspacing="0" class="moduletable">
							
							<tr>
              <th>View Options</th>
             
                 </tr>
                 <tr><td><ul><strong>Display by:</strong><li><a href=view_lastname.php>Last Name</a></li>
             <li> <a href=view_recent.php>Recent Entry</a></li>
             <li><a href=view_institution.php>Institution</a></li></ul><br />
             
             
            </td>
             </tr> 
             
             <tr>
              <td><div id="help"><p>Click on images to view the information in pop-up windows.</p></div></td>
             </tr> 
             
             
         
						</table> <!-- end module table -->
				<!--		 <table cellpadding="0" cellspacing="0" class="moduletable">
							<tr>
					<th valign="top">
					Add an Entry	</th>
				</tr>
								<tr>

					<td>
					<div><br /><ul>
                 <li> <a href=add_photo.php> Submit New Entry</a> </li>
            </ul></div>		</td>
				</tr>
				
				<tr><td valign=top align=left>
            <div id=help>
	
	
	<p><strong>Need help?</strong><br />If you experience problems adding your information to our facebook, 
			or if you need to make changes after your information is published, please email 
			<a href="mailto:shardin@umich.edu">shardin@umich.edu</a></p>
		   </div>
		</td></tr>
						</table>
-->

				<table cellpadding="0" cellspacing="0" class="moduletable">
							
							<tr>
              <th>Other Facebooks</th>
             
                 </tr>
                 <tr><td>
             
             
             <ul>
             
        
             <li> <a href="http://www.sakaiproject.org/facebook/index.php">Baltimore, June 2005</a></li>
             </ul><br /></td>
             </tr> 
             
          
             
             
         
						</table> <!-- end module table -->
			 

		 </div>  <!-- end left row -->
	    </td>   <!-- end left column of main section -->

						