<?php

//header information for facebook  
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Sakai Facebook - Austin Conference, December 2005</title>
<meta name="description" content="Sakai - www.sakaiproject.org, Community Source Software for Education." />
<meta name="keywords" content="sakai, sakaiproject.org, sakaiproject, Sakai, Community Source, Open Source, open-open, educational software, collaborative" />
<meta name="Generator" content="Mambo - Copyright 2000 - 2005 Miro International Pty Ltd.  All rights reserved." />
<meta name="robots" content="index, follow" />
<meta http-equiv="Content-Type" content="text/html;>charset=iso-8859-1" />
<link rel="stylesheet" href="http://www.sakaiproject.org/templates/247portal-b-brown2/css/template_css.css" type="text/css"/><link rel="alternate" title="sakaiproject.org" href="http://www.sakaiproject.org/index2.php?option=com_rss&no_html=1" type="application/rss+xml" />
<script language="JavaScript" type="text/javascript">
    <!--
    function MM_reloadPage(init) {  //reloads the window if Nav4 resized
      if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
        document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
      else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
    }
    MM_reloadPage(true);
    //-->
  </script>
<style type="text/css">
 input {
font-size: 12px;
padding-left: 3px;
}
#searchBar1{
border-top: 1px solid #eee;
border-bottom:1px solid #ccc;

padding: 0px spx;
margin: 0;
}

.searchBar, .searchBar form, .searchBar input{
padding: 0px 0px 0px 0px;
margin: 0px;


}
.searchBar form{
color: #660000;
}

#photos {
width: 100%;
padding:0px;
margin-top: 0px;
margin-left: 0px;

}

#photos a, #photos a:link, #photos a:visited{
font-weight: normal;
color: #4E6483;
color: #660000;


}
#photos a:hover{
font-weight: normal;
color: #ffcc33;

}

#help p, #help2 p{
width: 140px; 
border: 1px solid #eee;
font-size: 11px;
padding: 3px 3px 3px 10px;
text-align: left;


}
.goback a{ color: #660000;


}



#menu {width:100%;
padding: 0px 0px 0px 0px;
margin:0px;}


#menu td {
border-bottom: 1px solid #eee;
}


#menu ul{
display: block;
text-align: left;
}

#menu li {display: block;
padding: 2px 0px 0px 0px;
text-align: left;


}

.viewmenu {width:500px;
padding: 4px 0px 4px 40px;


}
.editmenu {
padding: 4px 0px;

}


#frame{
float: left;
text-align: left;
width: 135px;
height: 200px;
padding: 10px;
margin: 0px;
font-size: 10px;

}



#frame img {
padding: 0px;
border: 0px solid #eee;

}

#about, .name, .institute, .interests{
padding: 0px;

margin:0px;
}
.name {
font-size: 11px;

font-weight: bold;
padding: 2px 0px 0 0px;


}
.institute{ font-size: 10px;
padding: 0px 0px;

}
.interests {font-size: 10px;
padding: 5px  0px 0px 0px;
text-align:left;



}

div span.label{
font-weight: bold;
float: left;
width: 140px;
text-align: right;
}

div span.data{ 
text-align: left;
padding-left: 10px;

}

#info {padding: 0px 20px;

}
<!--
.Stil1 {font-size: xx-small;
	color: #FFFFFF;
}

.searchForm {width:300px; 
text-align: left;


}
-->
</style>
</head>

<body width=800px>
<div>
  <a name="up" id="up"></a>
  <table width="100%" height="20" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center" class="mt">&nbsp;</td>
    </tr>
  </table>  
  <table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>

    <td><img src="http://www.sakaiproject.org/templates/247portal-b-brown2/images/space.gif" width="770" height="1" /></td>
  </tr>
	<tr>
      <td><div class="background">
        <table width="100%"  border="0" cellpadding="0" cellspacing="0" background="http://www.sakaiproject.org/templates/247portal-b-brown2/images/center.jpg">
          <tr>
            <td width="26"><img src="http://www.sakaiproject.org/templates/247portal-b-brown2/images/left.jpg" width="26" /></td>
            <td class="title">              
            <table width="100%"  border="0" cellspacing="0" cellpadding="0">

              <tr>
                <td height="100" colspan="2" class="title" style="padding-top:14px;">
                <table width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                      <td width="100%" style="padding-left:10px;"><a href="http://www.sakaiproject.org" title="sakaiproject.org">sakaiproject.org</a><p><strong>4th Sakai Conference (with OSP), Austin Texas - 
December 7-9, 2005&nbsp;</strong></p></td>
                      <td>      <form class ="searchForm" method="post" action="search.php">
                    <label> Search Facebook</label>
                    <input type="text" name="searchword" size="15" maxlength="40" value="<?php echo $_POST['searchword']?>" />
                    <input type="submit" value="go" />
                  </form>
                </td>
                    </tr>
                </table>
                </td>
              </tr>

           
            </table></td>
            <td width="26"><img src="http://www.sakaiproject.org/templates/247portal-b-brown2/images/right.jpg" width="26" /></td>
          </tr>
        </table>
        <table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td width="11" height="25" background="http://www.sakaiproject.org/templates/247portal-b-brown2/images/shadowl.jpg"><div>
            </div></td>
            <td height="25" bgcolor="#F1F1F1" style="border-bottom: 1px solid #999999; border-top: 5px solid #FFFFFF;"><span class="pathway"><a href="http://sakaiproject.org/index.php" class="pathway">Home</a> <img src="http://www.sakaiproject.org/images/M_images/arrow.png" alt="arrow" />   Austin Conference <img src="http://www.sakaiproject.org/images/M_images/arrow.png" alt="arrow" />   Facebook </span>

</td>
            <td width="11" height="25" align="right" background="http://www.sakaiproject.org/templates/247portal-b-brown2/images/shadowr.jpg">&nbsp;</td>
          </tr>
        </table>
        <table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td valign="top" style="padding-left:8px; background-repeat: repeat-y;" background="http://www.sakaiproject.org/templates/247portal-b-brown2/images/shadowl.jpg">&nbsp;</td>
            <td valign="top" style="background-repeat: repeat-y;"background="http://www.sakaiproject.org/templates/247portal-b-brown2/images/lb.gif">    
            <div class="leftrow">

                			<table cellpadding="0" cellspacing="0" class="moduletable">
							<tr>
					<th valign="top">
										Austin Conference					</th>
				</tr>
							<tr>
				<td>
				
<table width="100%" border="0" cellpadding="0" cellspacing="0">

<tr align="left"><td><a href="http://www.sakaiproject.org/index.php?option=com_content&amp;task=blogcategory&amp;id=158&amp;Itemid=495" class="mainlevel" >Conference Home</a></td></tr>
<tr align="left"><td><a href="http://www.sakaiproject.org/index.php?option=com_content&task=blogcategory&id=159&Itemid=494" class="mainlevel" id="active_menu">Austin Facebook</a></td></tr>
<tr align="left"><td>&nbsp;<br /></td></tr>
<tr align="left"><td>
						<table cellpadding="0" cellspacing="0" class="moduletable">
							
							<tr>
              <th>View Options</th>
             
                 </tr><tr><td><ul><strong>Display by:</strong><li><a href=view_lastname.php>Last Name</a></li>
             <li> <a href=view_recent.php>Recent Entry</a></li>
             <li><a href=view_institution.php>Institution</a></li></ul><br /></div></td>
             </tr> 
             
             <tr>
              <td>&nbsp;</td>
             </tr> 
             
         
						</table></td></tr>
</table>				</td>

			</tr>
			</table>
						<table cellpadding="0" cellspacing="0" class="moduletable">
							<tr>
					<th valign="top">
					Add or Edit Entries 	</th>
				</tr>
								<tr>

					<td>
					<div><br /><ul>
                 <li> <a href=add_photo.php> Submit New Entry</a> </li>
               <li>   Edit Your Entry <br /><span class=small> (coming soon)</span></li></ul></div>		</td>
				</tr>
				
				<tr><td valign=top align=left>
            <div id=help>
	
	
	<p><strong>Need help?</strong><br />If you experience problems adding your information to our facebook, 
			or if you need to make changes after your information is published, please email 
			<a href="mailto:shardin@umich.edu">shardin@umich.edu</a></p>
		   </div>
		</td></tr>
						</table>