
             <!-- Footer Row begins-->
<tr><td colspan=2>
	<table width=100%>
 
            <tr class="creditsHere">

              <td align="center" valign="top"><div><p><br /><br /><br/><span class="small">Contact <a href="mailto:sakaiproject_webmaster@umich.edu">--Webmaster</a></span><br>
             <br /><br /></p> </div>
          
          
    		  </td>

   			 </tr>    <!-- Footer  - Row ends-->
		</table>


</td>
</tr>

</table>
</body>
</html>